export const CHANGE_TYPES = {
  CREATE: "CREATE_NODE",
  REMOVE: "REMOVE_NODE",
  REPLACE: "REPLACE_NODE",
  UPDATE_TEXT: "UPDATE_TEXT",
  SET_ATTRIBUTE: "SET_ATTRIBUTE",
  REMOVE_ATTRIBUTE: "REMOVE_ATTRIBUTE",
  MOVE_CHILD: "MOVE_CHILD",
};
